name: Gource and FFmpeg
description: Generate a video from the (combined) logs of SCM repositories.
inputs:
  logs:
    description: Path to the location of the logs.
    required: false
    default: './gource/logs'
  artifact:
    description: Name of the artifact containing the logs.
    required: false
    default: logs
  job:
    description: String object with fields 'name', 'title', 'tree' and 'args'.
    required: true

runs:
  using: 'composite'
  steps:

    - uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact }}
        path: ${{ inputs.logs }}

    - shell: python
      id: job
      run: |
        # Combine logs and generate video
        from pathlib import Path
        from subprocess import check_call

        LogDir = Path('${{ inputs.logs }}').resolve()
        CombinedDir = LogDir.parent / 'combined'
        CombinedDir.mkdir(exist_ok=True)

        job = ${{ inputs.job }}
        print(f"::set-output name=name::{job['name']!s}")

        for repo, loc in job['tree'].items():
            logFile = f"{repo.replace('/','--')}.log"
            check_call(['cp', str(LogDir / logFile), str(CombinedDir / logFile)])
            if (loc is None) or len(loc) == 0:
                continue
            check_call(['sed', '-i', '-r', f's#(.+)\|#\\1|/{loc}#', str(CombinedDir / logFile)])

        CombinedLog = CombinedDir.parent / 'combined.log'

        check_call(f'cat {CombinedDir!s}/*.log | sort -n > {CombinedLog!s}', shell=True)

        with CombinedLog.open('r') as fptr:
            clog = fptr.read().splitlines()
        with CombinedLog.open('w') as fptr:
            fptr.write(f'{clog[0].split("|")[0]}|Gource|A|/.root\n')
            fptr.write("\n".join(clog))

        check_call([
          "docker",
          "run",
          "--rm",
          "-v",
          f"{LogDir.parent!s}:/wrk",
          "-w",
          "/wrk",
          "-e", f"GOURCE_TITLE={job['title']}",
          "-e", f"GOURCE_NAME={job['name']}",
          "ghcr.io/umarcor/gource/xrun",
          "/xrun.sh",
        ] + (job['args'] if 'args' in job else []) + [
          "combined.log"
        ])

        check_call(['mv', str(LogDir.parent / f'{job["name"]}.mp4'), './'])
        check_call(['mv', str(LogDir.parent / f'{job["name"]}.jpg'), './'])

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.job.outputs.name }}
        path: |
          ${{ steps.job.outputs.name }}.mp4
          ${{ steps.job.outputs.name }}.jpg
        if-no-files-found: error
