EDAA:
  title: Electronic Design Automation Abstraction (EDAA)
  tree:
    <<: &EDAA-repos
      edaa-org/edaa-org.github.io: ~
      edaa-org/pyEDAA.ProjectModel: pyEDAA.ProjectModel
      edaa-org/pySVModel: pySVModel
      edaa-org/pyEDAA.IPXACT: pyEDAA.IPXACT
      edaa-org/pyEDAA.Reports: pyEDAA.Reports
      VHDL/pyVHDLModel: pyVHDLModel

EDAA-all:
  title: Electronic Design Automation Abstraction (EDAA) | Workflows
  tree:
    <<: *EDAA-repos
    cocotb/cocotb: Workflows/CoCoTb
    olofk/fusesoc: Workflows/LibreCores/FuseSoC
    olofk/edalize: Workflows/LibreCores/Edalize
    PyFPGA/pyfpga: Workflows/PyFPGA
    Paebbels/pyIPCMI: Workflows/pyIPCMI
    #: Workflows/tsfpga
    VUnit/vunit: Workflows/VUnit
    XedaHQ/xeda: Workflows/Xeda
    OSVVM/OSVVM-Scripts: Workflows/OSVVM-Scripts

ghdl:
  title: github.com/ghdl
  args:
    - --file-filter
    - ghdl/testsuite/vests
  tree:
    ghdl/ghdl: ghdl
    ghdl/ghdl-yosys-plugin: ghdl-yosys-plugin
    ghdl/ghdl-language-server: ghdl-language-server
    ghdl/ghdl-cosim: ghdl-cosim
    ghdl/docker: docker
    ghdl/extended-tests: extended-tests
    ghdl/setup-ghdl-ci: setup-ghdl-ci

osvvm:
  title: github.com/OSVVM
  tree:
    OSVVM/OsvvmLibraries: ~
    OSVVM/OSVVM-Scripts: Scripts
    OSVVM/UART: UART
    OSVVM/OSVVM: OSVVM
    OSVVM/Documentation: Documentation
    OSVVM/OSVVM-Common: Common
    OSVVM/AXI4: AXI4

osvb:
  title: Open Source Verification Bundle (OSVB)
  tree:
    umarcor/osvb: ~
    VUnit/vunit: mods/VUnit
    cocotb/cocotb: mods/cocotb
    OSVVM/OsvvmLibraries: mods/OSVVM/OsvvmLibraries
    OSVVM/OSVVM-Scripts: mods/OSVVM/OsvvmLibraries/Scripts
    OSVVM/UART: mods/OSVVM/OsvvmLibraries/UART
    OSVVM/OSVVM: mods/OSVVM/OsvvmLibraries/OSVVM
    OSVVM/Documentation: mods/OSVVM/OsvvmLibraries/Documentation
    OSVVM/OSVVM-Common: mods/OSVVM/OsvvmLibraries/Common
    OSVVM/AXI4: mods/OSVVM/OsvvmLibraries/AXI4
    svunit/svunit: mods/svunit
    uvvm/uvvm: mods/UVVM

osvb-noroot:
  title: Open Source Verification Bundle (OSVB)
  args:
    - --hide-root
  tree:
    umarcor/osvb: OSVB
    VUnit/vunit: VUnit
    cocotb/cocotb: cocotb
    OSVVM/OsvvmLibraries: OsvvmLibraries
    OSVVM/OSVVM-Scripts: OsvvmLibraries/Scripts
    OSVVM/UART: OsvvmLibraries/UART
    OSVVM/OSVVM: OsvvmLibraries/OSVVM
    OSVVM/Documentation: OsvvmLibraries/Documentation
    OSVVM/OSVVM-Common: OsvvmLibraries/Common
    OSVVM/AXI4: OsvvmLibraries/AXI4
    svunit/svunit: svunit
    uvvm/uvvm: UVVM

vunit:
  title: VUnit
  tree:
    VUnit/vunit: ~

hdlc:
  title: HDL Containers
  tree:
    hdl/containers: ~

neorv32:
  title: NEORV32
  tree:
    stnolting/neorv32: ~

cocotb:
  title: CoCoTb
  tree:
    cocotb/cocotb: ~

openFPGALoader:
  title: openFPGALoader
  tree:
    trabucayre/openFPGALoader:

spf13:
  title: Cobra, Viper and pflag
  args:
    - --hide-root
  tree:
    spf13/cobra: cobra
    spf13/viper: viper
    spf13/pflag: pflag
