EDAA:
  title: Electronic Design Automation Abstraction (EDAA)
  tree:
    <<: &EDAA-repos
      '': edaa-org/edaa-org.github.io
      pyEDAA.ProjectModel: edaa-org/pyEDAA.ProjectModel
      pySVModel: edaa-org/pySVModel
      pyEDAA.IPXACT: edaa-org/pyEDAA.IPXACT
      pyEDAA.Reports: edaa-org/pyEDAA.Reports
      pyVHDLModel: VHDL/pyVHDLModel

EDAA-all:
  title: Electronic Design Automation Abstraction (EDAA) | Workflows
  tree:
    <<: *EDAA-repos
    Workflows/CoCoTb: cocotb/cocotb
    Workflows/LibreCores/FuseSoC: olofk/fusesoc
    Workflows/LibreCores/Edalize: olofk/edalize
    Workflows/PyFPGA: PyFPGA/pyfpga
    Workflows/pyIPCMI: Paebbels/pyIPCMI
    #Workflows/tsfpga:
    Workflows/VUnit: VUnit/vunit
    Workflows/Xeda: XedaHQ/xeda
    Workflows/OSVVM-Scripts: OSVVM/OSVVM-Scripts

ghdl:
  title: github.com/ghdl
  args:
    - --file-filter
    - ghdl/testsuite/vests
  tree:
    ghdl: ghdl/ghdl
    ghdl-yosys-plugin: ghdl/ghdl-yosys-plugin
    ghdl-language-server: ghdl/ghdl-language-server
    ghdl-cosim: ghdl/ghdl-cosim
    docker: ghdl/docker
    extended-tests: ghdl/extended-tests
    setup-ghdl-ci: ghdl/setup-ghdl-ci

osvvm:
  title: github.com/OSVVM
  tree:
    '': OSVVM/OsvvmLibraries
    Scripts: OSVVM/OSVVM-Scripts
    UART: OSVVM/UART
    OSVVM: OSVVM/OSVVM
    Documentation: OSVVM/Documentation
    Common: OSVVM/OSVVM-Common
    AXI4: OSVVM/AXI4

vunit:
  title: VUnit
  tree:
    '': VUnit/vunit

hdlc:
  title: HDL Containers
  tree:
    '': hdl/containers

neorv32:
  title: NEORV32
  tree:
    '': stnolting/neorv32

cocotb:
  title: CoCoTb
  tree:
    '': cocotb/cocotb

openFPGALoader:
  title: openFPGALoader
  tree:
    '': trabucayre/openFPGALoader

cobra:
  title: Cobra
  tree:
    '': spf13/cobra
