EDAA:
  title: Electronic Design Automation Abstraction (EDAA)
  tree:
    <<: &EDAA-repos
      '': edaa-org/edaa-org.github.io
      pyEDAA.ProjectModel: edaa-org/pyEDAA.ProjectModel
      pySVModel: edaa-org/pySVModel
      pyEDAA.IPXACT: edaa-org/pyEDAA.IPXACT
      pyEDAA.Reports: edaa-org/pyEDAA.Reports
      pyVHDLModel: VHDL/pyVHDLModel

EDAA-all:
  title: Electronic Design Automation Abstraction (EDAA) | Workflows
  tree:
    <<: *EDAA-repos
    Workflows/CoCoTb: cocotb/cocotb
    Workflows/LibreCores/FuseSoC: olofk/fusesoc
    Workflows/LibreCores/Edalize: olofk/edalize
    Workflows/PyFPGA: PyFPGA/pyfpga
    Workflows/pyIPCMI: Paebbels/pyIPCMI
    #Workflows/tsfpga:
    Workflows/VUnit: VUnit/vunit
    Workflows/Xeda: XedaHQ/xeda
    Workflows/OSVVM-Scripts: OSVVM/OSVVM-Scripts

ghdl:
  title: github.com/ghdl
  args:
    - --file-filter
    - ghdl/testsuite/vests
  tree:
    ghdl: ghdl/ghdl
    ghdl-yosys-plugin: ghdl/ghdl-yosys-plugin
    ghdl-language-server: ghdl/ghdl-language-server
    ghdl-cosim: ghdl/ghdl-cosim
    docker: ghdl/docker
    extended-tests: ghdl/extended-tests
    setup-ghdl-ci: ghdl/setup-ghdl-ci

osvvm:
  title: github.com/OSVVM
  tree:
    '': OSVVM/OsvvmLibraries
    Scripts: OSVVM/OSVVM-Scripts
    UART: OSVVM/UART
    OSVVM: OSVVM/OSVVM
    Documentation: OSVVM/Documentation
    Common: OSVVM/OSVVM-Common
    AXI4: OSVVM/AXI4

osvb:
  title: Open Source Verification Bundle (OSVB)
  tree:
    '': umarcor/osvb
    mods/VUnit: VUnit/vunit
    mods/cocotb: cocotb/cocotb
    mods/OSVVM/OsvvmLibraries: OSVVM/OsvvmLibraries
    mods/OSVVM/OsvvmLibraries/Scripts: OSVVM/OSVVM-Scripts
    mods/OSVVM/OsvvmLibraries/UART: OSVVM/UART
    mods/OSVVM/OsvvmLibraries/OSVVM: OSVVM/OSVVM
    mods/OSVVM/OsvvmLibraries/Documentation: OSVVM/Documentation
    mods/OSVVM/OsvvmLibraries/Common: OSVVM/OSVVM-Common
    mods/OSVVM/OsvvmLibraries/AXI4: OSVVM/AXI4
    mods/svunit: svunit/svunit
    mods/UVVM: uvvm/uvvm

osvb-noroot:
  title: Open Source Verification Bundle (OSVB)
  args:
    - --hide-root
  tree:
    OSVB: umarcor/osvb
    VUnit: VUnit/vunit
    cocotb: cocotb/cocotb
    OsvvmLibraries: OSVVM/OsvvmLibraries
    OsvvmLibraries/Scripts: OSVVM/OSVVM-Scripts
    OsvvmLibraries/UART: OSVVM/UART
    OsvvmLibraries/OSVVM: OSVVM/OSVVM
    OsvvmLibraries/Documentation: OSVVM/Documentation
    OsvvmLibraries/Common: OSVVM/OSVVM-Common
    OsvvmLibraries/AXI4: OSVVM/AXI4
    svunit: svunit/svunit
    UVVM: uvvm/uvvm

vunit:
  title: VUnit
  tree:
    '': VUnit/vunit

hdlc:
  title: HDL Containers
  tree:
    '': hdl/containers

neorv32:
  title: NEORV32
  tree:
    '': stnolting/neorv32

cocotb:
  title: CoCoTb
  tree:
    '': cocotb/cocotb

openFPGALoader:
  title: openFPGALoader
  tree:
    '': trabucayre/openFPGALoader

spf13:
  title: Cobra, Viper and pflag
  args:
    - --hide-root
  tree:
    cobra: spf13/cobra
    viper: spf13/viper
    pflag: spf13/pflag
