# https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

github: [umarcor]
custom:
 - 'https://www.buymeacoffee.com/umarcor'
 - 'https://paypal.me/umarcor'
