name: Gource

on:
  push:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:

# https://github.com/acaudwell/Gource/wiki/Visualizing-Multiple-Repositories
# https://trac.ffmpeg.org/wiki/Encode/H.264


  Params:
    runs-on: ubuntu-latest
    outputs:
      cfg: ${{ steps.params.outputs.cfg }}
      jobs: ${{ steps.params.outputs.jobs }}
      mailmap: ${{ steps.params.outputs.mailmap }}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: Convert YAML config to JSON string
      id: params
      shell: python
      run: |
        from pathlib import Path
        from subprocess import check_call
        import yaml

        ROOT = Path('gource').resolve()
        LogDir = ROOT / 'logs'
        LogDir.mkdir(exist_ok=True)

        enabled = [
            'EDAA',
            'EDAA-all',
            'ghdl',
            'osvvm',
            'osvb',
            'osvb-noroot',
            'vunit',
            'hdlc',
            'neorv32',
            'cocotb',
            'openFPGALoader',
            'spf13',
        ]

        with (ROOT / 'config.yml').open('r') as fptr:
            cfg = yaml.load(fptr, Loader=yaml.FullLoader)
            for key in cfg:
                cfg[key]['name'] = key
            print(f"::set-output name=cfg::{cfg!s}")
            jobs = [
                {'name': key, 'title': job['title']}
                for key, job in cfg.items()
                if key in enabled
            ]
            print(f"::set-output name=jobs::{jobs!s}")

        with (ROOT / '.mailmap').open('r') as fptr:
            print(f"::set-output name=mailmap::{','.join(fptr.read().splitlines())!s}")


  GetLogs:
    needs: Params
    runs-on: ubuntu-latest
    steps:

    - run: |
        sudo apt update -qq
        sudo apt install -y gource

    - name: Generate list of jobs and get logs
      shell: python
      run: |
        from pathlib import Path
        from subprocess import check_call

        cfg = ${{ needs.Params.outputs.cfg }}
        LogDir = Path('logs').resolve()
        LogDir.mkdir(exist_ok=True)

        for repo in list(set([
            repo
            for _, job in cfg.items()
            for _, repo in job['tree'].items()
        ])):
            idx = f"{repo.replace('/','--')}"
            check_call(['git', 'clone', f'https://github.com/{repo}', idx])
            with (Path(idx) / '.mailmap').open('w') as fptr:
                fptr.write('''${{ needs.Params.outputs.mailmap }}'''.replace(',','\n'))
            check_call(['gource', '--output-custom-log', LogDir / f'{idx}.log', idx])

    - name: '📤 Upload artifact'
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs


  GenerateVideo:
    needs:
      - Params
      - GetLogs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.Params.outputs.jobs) }}
    name: ${{ matrix.name }} | ${{ matrix.title }}
    steps:

    - name: Get job from config
      shell: python
      id: job
      run: |
        job = ${{ needs.Params.outputs.cfg }}['${{ matrix.name }}']
        print(f"::set-output name=job::{job!s}")

    - name: Combine logs and generate video
      uses: umarcor/umarcor/gource@gource
      with:
        artifact: logs
        job: ${{ steps.job.outputs.job }}


  Release:
    needs: GenerateVideo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        path: artifact
    - run: |
        cd artifact
        tar czvf logs.tar.gz logs
        rm -rf logs
    - uses: eine/tip@master
      with:
        token: ${{ github.token }}
        files: artifact/**/*
        tag: gource-videos
