name: Images

on:
  push:
    paths:
      - '.github/workflows/Images.yml'
      - 'gource/containers/**'
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:

  Gource:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build container images
      run: |
        docker build -t ghcr.io/umarcor/gource -< gource/containers/Dockerfile
        docker build -t ghcr.io/umarcor/gource/xrun gource/containers -f- <<EOF
        FROM ghcr.io/umarcor/gource
        COPY run.sh /run.sh
        COPY xrun.sh /xrun.sh
        CMD ['/xrun.sh']
        EOF

    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: gha
        password: ${{ github.token }}

    - name: Push container images to registry
      run: for image in gource gource/xrun; do docker push ghcr.io/umarcor/"$image"; done
